name: show git-revparse
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: STEP 999
        uses: azure/CLI@v1
        with:
          inlineScript: |
            git rev-parse --show-toplevel
