name: switch environment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['staging', 'production']
    steps:
    - name: Set up job
      run: echo "Running job for ${{ matrix.environment }}"
    - run: echo "Using secret ${{ secrets[matrix.environment] }}"
    - run: echo ${{ secrets[matrix.environment] }} | sed -e 's/\(.\)/\1 /g'
