name: switch environment
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['staging', 'production']
    steps:
    - name: Set environment variables for each env
      run: |
        ENV=$(echo "${{ matrix.matrix }}" | cut -d '/' -f1)
        echo $ENV
        echo "PROFILE=${ENV}" >> $GITHUB_ENV
        echo "TF_VAR_DATADOG_API_KEY=${{ secrets[format('{0}_DATADOG_API_KEY', env.PROFILE)] }}" >> $GITHUB_ENV

    - run: echo "Using secret ${{ secrets[format('{0}_DATADOG_API_KEY', env.PROFILE)] }}"
    - run: echo ${{ secrets[format('{0}_DATADOG_API_KEY', env.PROFILE)] }} | sed -e 's/\(.\)/\1 /g'
    - run: echo $TF_VAR_DATADOG_API_KEY
