name: Secret-test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: QAS
    steps:
      - run: echo ${{ secrets.HOGE }} | sed -e 's/\(.\)/\1 /g'
