name: Secret-test
on:
  workflow_dispatch:
    inputs:
      testEnv:
        description: 'Which env ? (dev/sdv/qas):'
        required: true
        default: 'dev'

env:
  ENV_CODE: dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.ENV_CODE }}
    steps:
      - run: echo ${{ github.event.inputs.testEnv }}
      - run: echo ${{ secrets.HOGE }} | sed -e 's/\(.\)/\1 /g'
