name: show secret test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.HOGE }} | sed -e 's/\(.\)/\1 /g'
      - run: echo ${{ secrets.HOGE2 }} | sed -e 's/\(.\)/\1 /g'
